version: '3.8'
services:
  app:
    build: ./server
    restart: always
    ports:
      - "3000:3000"
    environment:
      # These variables will be read by config.js
      # For local development, you can create a .env file
      # For production, these should be set securely by your host or deployment system
      DB_HOST: 'db5018640333.hosting-data.io' # Use this on Docker Desktop to connect to localhost on the host machine
      DB_USER: 'dbu536762'
      DB_PASSWORD: 'Dag0D0g0503!'
      DB_NAME: 'dbs14774816'
      ADMIN_PASSWORD: 'supersecretpassword'
