on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Extract zip
    - uses: ihiroky/extract-action@v1
      with:
        file_path: ./client/solana-slots.com-main.zip
        extract_dir: ./client/solana
