            - name: Unzip and Update Repository Content
  # You may pin to the exact commit or the version.
  # uses: moehami/unzip-and-update-action@b81732593aa0a7be63d817283f37dc1687c12fdf
  uses: moehami/unzip-and-update-action@Unzip
  with:
    # Path to the zip file to extract, relative to the repository root.
    zip_file_path: /client/solona.zip
    # Comma-separated list of directories to remove before moving new content (e.g., css,en,fonts,js).
    target_directories_to_clean: # optional, default is 
    # If the zip extracts to a subfolder (e.g., zip contains "project_root/index.html"), specify "project_root".
    extracted_subfolder:/client/solona/
    # optional, default is 
          
